#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# harness/env_gen.sh — generate a service .env from .secrets + env.defaults
#
# Usage:
#   ./harness/env_gen.sh [service]            write services/<svc>/.env
#   ./harness/env_gen.sh [service] --print    print to stdout only
#   ./harness/env_gen.sh [service] --railway  print railway variables set commands
#
# Examples:
#   ./harness/env_gen.sh                      # intelligence (default)
#   ./harness/env_gen.sh intelligence --railway | bash
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail

HARNESS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$HARNESS_DIR/.." && pwd)"

SERVICE="${1:-intelligence}"
MODE="${2:-}"   # --print | --railway | ""

SECRETS_FILE="$ROOT/.secrets"
SERVICE_DIR="$ROOT/services/$SERVICE"
DEFAULTS_FILE="$SERVICE_DIR/env.defaults"
OUTPUT_FILE="$SERVICE_DIR/.env"

# ── Validation ─────────────────────────────────────────────────────────────

if [ ! -d "$SERVICE_DIR" ]; then
  echo "✗ Service '$SERVICE' not found at $SERVICE_DIR" >&2
  echo "  Available services:" >&2
  ls "$ROOT/services/" 2>/dev/null | sed 's/^/    /' >&2
  exit 1
fi

if [ ! -f "$SECRETS_FILE" ]; then
  echo "✗ .secrets not found at $ROOT/.secrets" >&2
  echo "  Copy the template and fill in your keys:" >&2
  echo "    cp secrets.example .secrets" >&2
  exit 1
fi

# ── Parse key=value files, skipping comments and blanks ────────────────────

declare -A VARS

_load_file() {
  local file="$1"
  [ -f "$file" ] || return 0
  while IFS= read -r line || [ -n "$line" ]; do
    # Strip inline comments after a space
    line="${line%%  #*}"
    [[ "$line" =~ ^[[:space:]]*# ]] && continue
    [[ "$line" =~ ^[[:space:]]*$ ]] && continue
    [[ "$line" != *=* ]] && continue
    local key="${line%%=*}"
    local val="${line#*=}"
    # Strip surrounding quotes
    val="${val#\"}" ; val="${val%\"}"
    val="${val#\'}" ; val="${val%\'}"
    key="${key// /}"  # trim whitespace from key
    [ -n "$key" ] && VARS["$key"]="$val"
  done < "$file"
}

_load_file "$DEFAULTS_FILE"   # defaults first — secrets override
_load_file "$SECRETS_FILE"

if [ "${#VARS[@]}" -eq 0 ]; then
  echo "✗ No variables found in .secrets or env.defaults" >&2
  exit 1
fi

# ── Output ──────────────────────────────────────────────────────────────────

case "$MODE" in

  --railway)
    echo "# Railway variable set commands for service: $SERVICE"
    for key in "${!VARS[@]}"; do
      printf 'railway variables set "%s=%s"\n' "$key" "${VARS[$key]}"
    done
    ;;

  --print)
    echo "# $SERVICE environment — $(date)"
    for key in "${!VARS[@]}"; do
      printf '%s=%s\n' "$key" "${VARS[$key]}"
    done
    ;;

  *)
    {
      echo "# Generated by harness/env_gen.sh — do not commit"
      echo "# Service: $SERVICE — $(date)"
      for key in "${!VARS[@]}"; do
        printf '%s=%s\n' "$key" "${VARS[$key]}"
      done
    } > "$OUTPUT_FILE"
    echo "✓ Written: $OUTPUT_FILE"
    ;;

esac
